# Generated by Django 3.2.18 on 2023-03-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='№')),
                ('order_number', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='заказ №')),
                ('price_usd', models.PositiveIntegerField(verbose_name='стоимость,$')),
                ('price_rub', models.FloatField(verbose_name='стоимость,руб')),
                ('shipping_date', models.DateTimeField(verbose_name='срок поставки')),
            ],
        ),
    ]
